name: material_purchase_app
description: "Material Purchase App with Flutter BloC and Clean Architecture"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  cool_alert: ^2.0.1
  country_code_picker: ^3.2.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.0
  http: ^1.3.0
  http_parser: ^4.1.1
  intl: ^0.20.2
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  loader_overlay: ^5.0.0
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  path: ^1.9.0
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf

